version: '3.7'
services:
  database:
    image: postgres
    container_name: wallet-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_pharmacy
      - POSTGRES_PASSWORD=Oficial1@3
      - POSTGRES_DB=pharmacy
    volumes:
      - pdgata:/data/postgres
  api:
    build: .
    container_name: pharmacy_api
    ports:
      - 3333:3333
    volumes:
      - .:/pharmacy
      - /pharmacy/node_modules
    links:
      - database
    depends_on:
      - database

volumes:
  pdgata:
    driver: local
